name: Test
on:
  push:
    branches:
    - main
    - dev/*
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.5'

    - name: Install dependencies
      run: |
        go get -u golang.org/x/lint/golint

    - name: Run vet and lint
      run: |
        go vet ./...
        golint ./...

    - name: Test
      run: |
        go test ./... -v
